# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
# bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
# bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
# bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
# bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
# bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
# bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
# bindd = SUPER SHIFT, B, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, O, Teams, exec, omarchy-launch-webapp "https://outlook.office.com/"
bindd = SUPER SHIFT, T, Outlook, exec, omarchy-launch-webapp "https://teams.cloud.microsoft/"
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, V, Bitwarden, exec, omarchy-launch-or-focus bitwarden
#bindd = SUPER SHIFT, V, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings
unbind = SUPER SHIFT, SLASH
unbind = SUPER, L
unbind = SUPER, K
unbind = SUPER, J
unbind = SUPER, H
unbind = SUPER, S
unbind = SUPER, SPACE

bindd = SUPER, m, Omarchy menu, exec, omarchy-menu
bindd = SUPER, S, Screenshot selection, exec, bash ~/.config/omarchy-supplement/bin/screenshot-select.sh

bind = SUPER SHIFT, Q, killactive
bind = SUPER, R, exec, walker
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d
